language: java

jdk:
- oraclejdk8

sudo: false

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

script: "./gradlew --info check jacocoRootTestReport"

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
- provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    branch: develop
    condition: "$TRAVIS_TAG =~ ^(\d+(\.\d+){1,2}(\.\*)?)-SNAPSHOT$"
- provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master
    condition: "$TRAVIS_TAG =~ ^(\d+(\.\d+){1,2}(\.\*)?)$"

env:
  global:
  - secure: Rhx9UeSCL12Q9ZMcqebSHoKk7DxXUrtU3o7xXp4kWiqUidIqxaB7+Gy3mLnAvRTaxOvGjkL8PsQDSSdVo4VBmiMoWYHk4gHoxKB9Lakzoa+sPBw3c0ufAbtOdSinkfNwL8wpVsNrioGrrkWOAOHY3b1h6IR2kE42lGFqF5TX5+pi5I6tXbYfG/9VnR5UoHQ9NXl/qGUX0fTYvXiIl8u/SO36pHXpA75yV5Ba+bPmYd1ZSFk+r1to2ExE7FYp81JutFmL44GddUKgZjBxQfjQjj3ExI0Hi6XNG9Wwr8tXSMHZ8rhGh8hXdCMGiMZ7xrfITKSyo4g9Hr3/3SFFeGEDDU+JYmsJ7v3JktA/56VKUhj9j6jSlyN9UK7wO+jDgSf8uOZmzPd3v0gvI3d8T0Qny3NKUSWc0Eo5fZK26sWkMPx8z0lYnejj9Nojpd59EsnpgDh6ix32jJ6JO5CKoLagNLrLmME3ulGZw9uMURZGxax/vVVsu1HHKNpasqrtllX6WQCXHqPIxcyOtsBFvanasfvDOLEFtSkOub1cHWDfHtbKg80SuY3BGkjW8qq+ngVE/RfZ/8kg6eZuUCTsOYquyBQNrPKQYP0OE+V4WqLWkK8Mu310ruQTZ3ivuncasWVDKjXDgEs1vSAJwSlA3s9tvIoKA19pEZHw0KfQ/WfgGAY=
  - secure: Br532+f+Zqfg+cxR+twZ9qNBdwiMQjAfvDNjU01hLWuP2A97yAj3OnoXcOSbcLhJi3l4jUnDfUpUuRkbfdIN+Hq/7lSRfjZOLf4kl+sonp5YE9AwKT8ZjfpkNBVNWI/Ua8/LbzOHWDqsiA5rAAtlHqsOQaU9OCUYCDKowtep9+L7lGEaKcbDOQtjNVD7EvCSK8NU71wbQxVkrzO2KBClyJPAuNw88rf27n/llH2VsnEIKfUjotRCqdxpznoEXeNtlHIZ/Sv3pMY7j4Qbsuf2+S2rzdpfdTqTvNXOIdNHBozZL0K8YQUqSbNEl70wWosKXildom55AImRPcTUG2sNbwWZzBSfSBmFT1MWwHYmyamTwzUv2QZjbABSNQEfOOAnmUv2YUtrWkfQGYpDrYjmcwzeGtKdRbHDccgGZpKleUy5A9BLUYcpmsRTwhniJtVzjzsiouZ5zmLFA7byCNn/UACyvTyWWhB7iTfMzO/z43lp7Lkm+qScpz6PBnBr6BWRhyq2UudEiQdR7eXfLr/OCbLMjY9HzqIonZgwe9XiDElN/4qv5Hf1O1FNuJYeT7H2BhBV1F7q3GvtilRhxWXxbWOd29vyUqNSJzLGjJNwIGI1gTMWvVGScxLNkf5iFeWCC/mg0Phdapz5CTixo6MKXmbIb3idk6aCUBjvcllUCxc=
  - secure: RfIJj9PCCLJNj6Gb6CFLIu5dOJvboAfaaPSw05cIFO9luf4VMRP0nkQX+PBBzmOmde5qurFLpf/5ehQdkf8JPUOsbKiOADWgys3JFp7IrVKfFTsN28VPzvA44vRA3z2MQMRstTBHw419stmjiK690RP8gMOalTtlLgWsW31c2pxhlk70KKI3nhJhH5a5ewzPGiU0ZzkTpQjemXxA02yX3THtYOPa0WesjMh67YpYKZhGsgPl0/mxZE8D2h7VHI9uOf972vSoAkuRldMpANyEYtG6empAp6jem+R12Xiv/UByQdG0UMhteDJM2tGq61cfNlWILETV/sy3CU6hCkJIS/9CNte4xxCLxcpGNA6QLi0/7e6L/AlvYRMZI9vD/pPas7yiUVtCuLZGIe0B0CGZG3VCYLCEcTZFMyA5FPxvd4wnck75vH1435c39/OKkma062h6p9ExRX4fe1bzq6UwzNncPr3yDk2VY6P92mxEL2i+vOhV/jKAV2NWMp4fUdKyhd4P/HvjWRZkbU0yQKMiNF3I/Z4KBRwVS/56/fOPKSvG4pnWfC2WR8OfiSfV5LFK7i/mCik7MUZT1zj5LmGt7Gi879c3npYDrtHdNC1rr9Yqoay90uaHE0EPbvJnhdpnFQdI0qejl/N60KbmXtv7m+N73lzoeoKihwKD8z2j/zU=
  - secure: pMIhDbtpmKghbs8+9eV1vKosT7dIca9prvLEXVDpnmPiBMNCDm145qo+67b2kiYSmp7tnhKbIGSMW25dCf7olwzeu7EThy2G61+yPUcbtCBwdHLBylLsSneRHflaJ05DQblQH+cQWnL5mNAA2w6Sx32ua0iwNh8YMTyqBaCphbvqEgBbIIpPoOwCkZalaJvuMTwZ/LAjKarec9xrpqy2YJVr3quL/64OVGpjfBVW2qPBIAzHBxq0YKckVvp3sr2nW1Jm8RR46/juxDRdA6bjw31VSXoUZrGAyjK6u2TwRuTxJk5LdabVxYupCwrIdggs3s7yLXpNBFQpQpXGoiZkRVv8IO8lgznON/1Y5CAJ1sD0xlZCAHNIN99M394KavTGcaTN/EFu23xCPFfVFFOjF7LQkJ6QlRWhLVDndN3I3IWzAzFmQWVFMaKTjDeH8KAeHEhdDvaGuJgAsH5Dj2h4cFDQnWRHgAVQwD02U6yOuI0871Cs2QD3ReB4R9USwVY63vxKpx6xNDvzDue1U5jRc2Z2kM6e3OGmyGQfA/dTp23t64TboAUxznGzMS8WoJTfBgu3RCmb6ey9gosGiouLxgvTgZ+ZwuHExIzPM6Efc3C2dpQ+mEynv14kdHVvFIFh1+B9UHhH3pJjlnyKsIIric766UxWfqWNUUfJyMLaZC8=
